#' @title database configuration
#' @description Creates the corresponding mapic db configuration object containing the database configuration details.
#'
#' @param db_type String describing the type of database to use. Options are
#' "data.frame", "csv" and "SQLite".
#' @param location A string with the location of the database. For data frame, the name of the object; for csv and SQLite the path to the file; for others the server.
#' @param table_name A string with the name of the table. Not necessary for csv and data frame.
#'
#' @return Returns an S3 object of different class (mapic db configuration object),
#' depending on the type of database selected.
#'
#' @details The function returns and object of the corresponding class, depending of the database specified:
#' \itemize{
#'  \item "data.frame" returns object of class "mdb_df". Here,
#' all the data obtained from the API
#' connection is stored internally in R only, which means that by clossing
#' the session the information will disappear. When the object \code{mdb_df} is
#' passed to \code{\link{db_load}}, it creates a data frame in the global environment
#' with the name specified in \code{location}. Therefore, it is important that an
#' object with the same name does not exist yet, or it will create a conflict.
#'  \item "csv" returns object of class "mdb_csv". It uses a text-based csv file
#' to store the data obtained from the API connection. When the object
#' \code{mdb_csv} is passed to \code{\link{db_load}}, it will create a csv file in the
#' path specified in \code{location}. It is recommended that such file is not
#' created manually or it can generate conflicts.
#'  \item "SQLite" returns object of class "mdb_SQLite". It uses SQLite as a
#' database. When the object \code{mdb_SQLite} is passed to \code{\link{db_load}},
#' it can generate both, the file and the table automatically, or if the file
#' already exists, it searches for the table. It is recommended that the table is
#' generated by the function and not manually.
#' It requires to have \href{https://www.sqlite.org/}{SQLite} installed in the system calling the function.
#'}
#'
#' @export
#'
database_configuration <- function(db_type,
                                   location,
                                   table_name) {
  if (tolower(db_type) == "data frame" || tolower(db_type) == "data.frame") {
    mdb_obj <- structure(
      list(location = location),
      class = c("mdb_df"))
  } else if (tolower(db_type) == "csv") {
    mdb_obj <- structure(
      list(location = location),
      class = c("mdb_csv"))
  } else if (tolower(db_type) == "sqlite") {
    mdb_obj <- structure(
      list(
        location = location,
        table = table_name),
      class = c("mdb_SQLite"))
  }
  return(mdb_obj)
}
